version: '2'
services:
  web:
    image: gestorpedidos
    ports:
      - 8081:8090
    depends_on:
      - gestorpedidosdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gestorpedidosdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_GENERATE-DDL=true
      - MAIL_EMAIL_AUTHENTICATION=<email>
      - MAIL_PASSWORD_AUTHENTICATION=<password>
      - MAIL_HOST_NAME=<hostname>
  gestorpedidosdb:
    container_name: gestorpedidosdb
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres